version: "3.5"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
  flask:
    build:
      context: flask_app
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./flask_app:/app
