version: "3.5"
services:
  frontend:
    image: zskpoznan/zastepstwa_frontend
    ports:
      - 80:80
    restart: always
  backend:
    image: zskpoznan/zastepstwa_backend
    ports:
      - 5000:5000
    restart: always
